version: '3'

services:
  bot:
    restart: unless-stopped
    environment:
      BOT_TOKEN: $BOT_TOKEN
      PUBLIC_KEY: $PUBLIC_KEY
      API_AUTH_KEY: $API_AUTH_KEY
      API_URL: $API_URL
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080