version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      AUTH_KEY: $AUTH_KEY # this will have use when I add authentication soon
      DB_URI: postgresql://postgres:postgres@postgres:5432/api
    ports:
      - 3000:3000
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data